version: "3.8"

networks:
  website:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/logs:/var/log/nginx
    depends_on:
      - php
      - mysql
    networks:
      - website

  mysql:
    image: mariadb:10.5.8
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - website

  php:
    build:
      context: .
      dockerfile: ./.docker/php/dev/Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./.docker/php/dev/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - website

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "81:80"
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 20000000
    depends_on:
      - php
      - mysql
    networks:
      - website
